pipeline:
  build:
    image: docker:1.11
    commands:
      - docker build -t drone-test .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

services:
  redis:
    image: redis:latest
  mongo:
    image: mongo:3.2.4

