pipeline:
  build:
    image: docker:1.11
    commands:
      - apk --update add php5 php5-openssl php5-phar php5-json php5-zlib && php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php && php composer-setup.php && php -r "unlink('composer-setup.php');" && mv composer.phar /usr/local/bin/composer
      - composer install
      - vendor/bin/phpunit
      - docker build -t drone-test .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

services:
  redis:
    image: redis:latest
  mongo:
    image: mongo:3.2.4

